### ISSUE TITLE
Fatal error when importing from a CSV file

### ISSUE THREAD

**Issue by jackaponte** [backdrop-contrib/feeds#2]
I've configured a Feeds importer with no problems, but when trying to run an import of a CSV into nodes using a standalone form I get this fatal error after clicking the "Import" button:

`Fatal error: Class 'JobScheduler' not found in /var/www/sitename/modules/feeds/includes/FeedsSource.inc on line 314`

I've done a bit of digging but can't sort out the problem; Job Scheduler is also installed and enabled. Has anyone else run across this problem?

**Comment by Al-Rozhkov** [comment]
I was able to import from manually uploaded csv file without any problem.

@jackaponte, do you still get this error with latest version of Feeds?

**Comment by Dogbombs** [comment]
Yes, I can confirm that I get this issue with the latest version of Feeds.  Only the line reference is now line 311 rather than 314.  I'm going to remove Feeds completely, then re-install and see if the error persists.

**Comment by docwilmot** [comment]
I suspect this may have been fixed. Please reopen if it isnt

**Comment by t4k** [comment]
Just a note here. I’m still getting this error with the latest release. It occurs both with an uploaded CSV as well as a CSV available at a URL.
> Error: Class 'JobScheduler’ not found in FeedsSource->scheduleImport() (line 311 of /var/www/backdrop/modules/feeds/includes/FeedsSource.inc).

In order to overcome it I had to download the master branch of `job_scheduler`, not the tagged release.

**Comment by docwilmot** [comment]
Done.

**Comment by t4k** [comment]
This works cleanly now for me with no issues using the newly released Job Scheduler 1.1.2.
